/*
 * $FILE: hm.c
 *
 * health monitor management functions
 *
 * $VERSION$
 *
 * Authors: Miguel Masmano <mmasmano@ai2.upv.es>
 *
 * $LICENSE:
 * COPYRIGHT (c) Fent Innovative Software Solutions S.L.
 *     Read LICENSE.txt file for the license terms.
 */
/*
  Changelog:
  - [18/11/2015:SPR-221015-01] XM_HM_EV_SPARCV8_UNCORRECTABLE_EDAC_ERROR added
*/

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "common.h"
#include "xmc.h"

#define FILL_TAB(x) [x]=#x

char *hmLog[2]={
    FILL_TAB(XM_HM_LOG_DISABLED),
    FILL_TAB(XM_HM_LOG_ENABLED),
};

char *hmActions[XM_HM_MAX_ACTIONS]={
    FILL_TAB(XM_HM_AC_IGNORE),
    FILL_TAB(XM_HM_AC_PARTITION_COLD_RESET),
    FILL_TAB(XM_HM_AC_PARTITION_WARM_RESET),
    FILL_TAB(XM_HM_AC_HYPERVISOR_COLD_RESET),
    FILL_TAB(XM_HM_AC_HYPERVISOR_WARM_RESET),
    FILL_TAB(XM_HM_AC_SUSPEND),
    FILL_TAB(XM_HM_AC_HALT),
    FILL_TAB(XM_HM_AC_PROPAGATE),
    FILL_TAB(XM_HM_AC_SWITCH_TO_MAINTENANCE),
};

char *hmEvents[XM_HM_MAX_EVENTS]={
    FILL_TAB(XM_HM_EV_INTERNAL_ERROR),
    FILL_TAB(XM_HM_EV_UNEXPECTED_TRAP),
    FILL_TAB(XM_HM_EV_PARTITION_UNRECOVERABLE),
    FILL_TAB(XM_HM_EV_PARTITION_ERROR),
    FILL_TAB(XM_HM_EV_PARTITION_INTEGRITY),
    FILL_TAB(XM_HM_EV_MEM_PROTECTION),
    FILL_TAB(XM_HM_EV_OVERRUN),
    FILL_TAB(XM_HM_EV_SCHED_ERROR),
    FILL_TAB(XM_HM_EV_WATCHDOG_TIMER),
    FILL_TAB(XM_HM_EV_INCOMPATIBLE_INTERFACE),
    FILL_TAB(XM_HM_EV_EXTSYNC_ERROR),
#ifdef CONFIG_SPARCv8
    FILL_TAB(XM_HM_EV_SPARCV8_WRITE_ERROR),
    FILL_TAB(XM_HM_EV_SPARCV8_INSTR_ACCESS_MMU_MISS),
    FILL_TAB(XM_HM_EV_SPARCV8_INSTR_ACCESS_ERROR),
    FILL_TAB(XM_HM_EV_SPARCV8_REGISTER_HARDWARE_ERROR),
    FILL_TAB(XM_HM_EV_SPARCV8_INSTR_ACCESS_EXCEPTION),
    FILL_TAB(XM_HM_EV_SPARCV8_PRIVILEGED_INSTR),
    FILL_TAB(XM_HM_EV_SPARCV8_ILLEGAL_INSTR),
    FILL_TAB(XM_HM_EV_SPARCV8_FP_DISABLED),
    FILL_TAB(XM_HM_EV_SPARCV8_CP_DISABLED),
    FILL_TAB(XM_HM_EV_SPARCV8_UNIMPLEMENTED_FLUSH),
    FILL_TAB(XM_HM_EV_SPARCV8_WATCHPOINT_DETECTED),
    FILL_TAB(XM_HM_EV_SPARCV8_MEM_ADDR_NOT_ALIGNED),
    FILL_TAB(XM_HM_EV_SPARCV8_FP_EXCEPTION),
    FILL_TAB(XM_HM_EV_SPARCV8_CP_EXCEPTION),
    FILL_TAB(XM_HM_EV_SPARCV8_DATA_ACCESS_ERROR),
    FILL_TAB(XM_HM_EV_SPARCV8_DATA_ACCESS_MMU_MISS),
    FILL_TAB(XM_HM_EV_SPARCV8_DATA_ACCESS_EXCEPTION),
    FILL_TAB(XM_HM_EV_SPARCV8_TAG_OVERFLOW),
    FILL_TAB(XM_HM_EV_SPARCV8_DIVIDE_EXCEPTION),
    FILL_TAB(XM_HM_EV_SPARCV8_UNCORRECTABLE_EDAC_ERROR),
#endif
    FILL_TAB(XM_HM_EV_APP_DEADLINE_MISSED), 
    FILL_TAB(XM_HM_EV_APP_APPLICATION_ERROR), 
    FILL_TAB(XM_HM_EV_APP_NUMERIC_ERROR), 
    FILL_TAB(XM_HM_EV_APP_ILLEGAL_REQUEST), 
    FILL_TAB(XM_HM_EV_APP_STACK_OVERFLOW), 
    FILL_TAB(XM_HM_EV_APP_MEMORY_VIOLATION), 
    FILL_TAB(XM_HM_EV_APP_HARDWARE_FAULT), 
    FILL_TAB(XM_HM_EV_APP_POWER_FAIL), 
};

xm_u32_t ToHmAction(char *s, int line) {
    int e;
    for (e=0; e<XM_HM_MAX_ACTIONS; e++)
	if (hmActions[e]&&!strcmp(s, hmActions[e]))
	    return e;
    
    LineError(line, "Expected a valid Health Monitor action");
    return 0;
}

xm_u32_t ToHmEvent(char *s, int line) {
     int e;
    for (e=0; e<XM_HM_MAX_EVENTS; e++)
	if (hmEvents[e]&&!strcmp(s, hmEvents[e]))
	    return e;
   
    LineError(line, "Expected a valid Health Monitor event");
    return 0;
}

#define TOBIT(x) (1<<x)

static xm_u32_t hmPartEventsAndActions[XM_HM_MAX_EVENTS]= {
    [XM_HM_EV_INTERNAL_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_UNEXPECTED_TRAP]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_PARTITION_UNRECOVERABLE]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_PARTITION_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_PARTITION_INTEGRITY]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_MEM_PROTECTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_OVERRUN]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SCHED_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_WATCHDOG_TIMER]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_INCOMPATIBLE_INTERFACE]=TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

#ifdef CONFIG_SPARCv8
    [XM_HM_EV_SPARCV8_WRITE_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SPARCV8_INSTR_ACCESS_MMU_MISS]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SPARCV8_INSTR_ACCESS_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SPARCV8_INSTR_ACCESS_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARCV8_ILLEGAL_INSTR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARCV8_PRIVILEGED_INSTR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARCV8_FP_DISABLED]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARCV8_CP_DISABLED]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARCV8_UNIMPLEMENTED_FLUSH]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SPARCV8_WATCHPOINT_DETECTED]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SPARCV8_REGISTER_HARDWARE_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARCV8_MEM_ADDR_NOT_ALIGNED]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARCV8_FP_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARCV8_CP_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SPARCV8_DATA_ACCESS_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SPARCV8_DATA_ACCESS_MMU_MISS]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SPARCV8_DATA_ACCESS_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARCV8_TAG_OVERFLOW]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARCV8_DIVIDE_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    [XM_HM_EV_SPARCV8_UNCORRECTABLE_EDAC_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

#endif
    [XM_HM_EV_APP_DEADLINE_MISSED]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE), 

    [XM_HM_EV_APP_APPLICATION_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE), 

    [XM_HM_EV_APP_NUMERIC_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE), 

    [XM_HM_EV_APP_ILLEGAL_REQUEST]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE), 

    [XM_HM_EV_APP_STACK_OVERFLOW]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE), 

    [XM_HM_EV_APP_MEMORY_VIOLATION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE), 

    [XM_HM_EV_APP_HARDWARE_FAULT]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE), 

    [XM_HM_EV_APP_POWER_FAIL]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_PARTITION_COLD_RESET)|TOBIT(XM_HM_AC_PARTITION_WARM_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE), 
};


static xm_u32_t hmHpvEventsAndActions[XM_HM_MAX_GENERIC_EVENTS+XM_HM_MAX_ARCH_EVENTS]= {
    [XM_HM_EV_INTERNAL_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_UNEXPECTED_TRAP]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_PARTITION_UNRECOVERABLE]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_PARTITION_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_PARTITION_INTEGRITY]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_MEM_PROTECTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_OVERRUN]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SCHED_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_WATCHDOG_TIMER]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_INCOMPATIBLE_INTERFACE]=TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_EXTSYNC_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
#ifdef CONFIG_SPARCv8
    [XM_HM_EV_SPARCV8_WRITE_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SPARCV8_INSTR_ACCESS_MMU_MISS]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARCV8_INSTR_ACCESS_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SPARCV8_INSTR_ACCESS_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARCV8_ILLEGAL_INSTR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARCV8_PRIVILEGED_INSTR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARCV8_FP_DISABLED]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARCV8_CP_DISABLED]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARCV8_UNIMPLEMENTED_FLUSH]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SPARCV8_WATCHPOINT_DETECTED]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SPARCV8_REGISTER_HARDWARE_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARCV8_MEM_ADDR_NOT_ALIGNED]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARCV8_FP_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SPARCV8_CP_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARCV8_DATA_ACCESS_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARCV8_DATA_ACCESS_MMU_MISS]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SPARCV8_DATA_ACCESS_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARCV8_TAG_OVERFLOW]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
    
    [XM_HM_EV_SPARCV8_DIVIDE_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),

    [XM_HM_EV_SPARCV8_UNCORRECTABLE_EDAC_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_HYPERVISOR_COLD_RESET)|TOBIT(XM_HM_AC_HYPERVISOR_WARM_RESET)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_SWITCH_TO_MAINTENANCE),
#endif
};

static struct xmcHmSlot defaultPartHmTab[XM_HM_MAX_EVENTS]={
    [XM_HM_EV_INTERNAL_ERROR]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_UNEXPECTED_TRAP]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_PARTITION_UNRECOVERABLE]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_PARTITION_ERROR]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_PARTITION_INTEGRITY]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_MEM_PROTECTION]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_OVERRUN]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SCHED_ERROR]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_WATCHDOG_TIMER]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_INCOMPATIBLE_INTERFACE]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
#ifdef CONFIG_SPARCv8
    [XM_HM_EV_SPARCV8_WRITE_ERROR]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARCV8_INSTR_ACCESS_MMU_MISS]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARCV8_INSTR_ACCESS_ERROR]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_INSTR_ACCESS_EXCEPTION]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_ILLEGAL_INSTR]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARCV8_PRIVILEGED_INSTR]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_FP_DISABLED]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARCV8_CP_DISABLED]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARCV8_UNIMPLEMENTED_FLUSH]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARCV8_WATCHPOINT_DETECTED]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARCV8_REGISTER_HARDWARE_ERROR]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_MEM_ADDR_NOT_ALIGNED]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARCV8_FP_EXCEPTION]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARCV8_CP_EXCEPTION]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARCV8_DATA_ACCESS_ERROR]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_DATA_ACCESS_MMU_MISS]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARCV8_DATA_ACCESS_EXCEPTION]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_TAG_OVERFLOW]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARCV8_DIVIDE_EXCEPTION]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_DISABLED, },
    [XM_HM_EV_SPARCV8_UNCORRECTABLE_EDAC_ERROR]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
#endif
    [XM_HM_EV_APP_DEADLINE_MISSED]={.action=XM_HM_AC_IGNORE, .log=XM_HM_LOG_DISABLED, }, 
    [XM_HM_EV_APP_APPLICATION_ERROR]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_DISABLED, }, 
    [XM_HM_EV_APP_NUMERIC_ERROR]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_DISABLED, }, 
    [XM_HM_EV_APP_ILLEGAL_REQUEST]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_DISABLED, }, 
    [XM_HM_EV_APP_STACK_OVERFLOW]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_DISABLED, }, 
    [XM_HM_EV_APP_MEMORY_VIOLATION]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_DISABLED, }, 
    [XM_HM_EV_APP_HARDWARE_FAULT]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_DISABLED, }, 
    [XM_HM_EV_APP_POWER_FAIL]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_DISABLED, }, 
};


static struct xmcHmSlot defaultHpvHmTab[XM_HM_MAX_GENERIC_EVENTS+XM_HM_MAX_ARCH_EVENTS]={
    [XM_HM_EV_INTERNAL_ERROR]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_UNEXPECTED_TRAP]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_PARTITION_UNRECOVERABLE]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_PARTITION_ERROR]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_PARTITION_INTEGRITY]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_MEM_PROTECTION]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_OVERRUN]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SCHED_ERROR]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_WATCHDOG_TIMER]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_INCOMPATIBLE_INTERFACE]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_EXTSYNC_ERROR]={.action=XM_HM_AC_IGNORE, .log=XM_HM_LOG_ENABLED, },
#ifdef CONFIG_SPARCv8
    [XM_HM_EV_SPARCV8_WRITE_ERROR]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_INSTR_ACCESS_MMU_MISS]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_INSTR_ACCESS_ERROR]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_INSTR_ACCESS_EXCEPTION]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_ILLEGAL_INSTR]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_PRIVILEGED_INSTR]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_FP_DISABLED]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_CP_DISABLED]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_UNIMPLEMENTED_FLUSH]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_WATCHPOINT_DETECTED]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_REGISTER_HARDWARE_ERROR]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_MEM_ADDR_NOT_ALIGNED]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_FP_EXCEPTION]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_CP_EXCEPTION]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_DATA_ACCESS_ERROR]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_DATA_ACCESS_MMU_MISS]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_DATA_ACCESS_EXCEPTION]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_TAG_OVERFLOW]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_DIVIDE_EXCEPTION]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SPARCV8_UNCORRECTABLE_EDAC_ERROR]={.action=XM_HM_AC_HALT, .log=XM_HM_LOG_ENABLED, },
#endif
};

void SetupDefaultHpvHmActions(struct xmcHmSlot *hmTab) {
    memcpy(hmTab, defaultHpvHmTab, sizeof(struct xmcHmSlot)*(XM_HM_MAX_GENERIC_EVENTS+XM_HM_MAX_ARCH_EVENTS));
}

void SetupDefaultPartHmActions(struct xmcHmSlot *hmTab) {
    memcpy(hmTab, defaultPartHmTab, sizeof(struct xmcHmSlot)*XM_HM_MAX_EVENTS);
}


void HmHpvIsActionPermittedOnEvent(int event, int action, int line) {
    if (event >= XM_HM_MAX_GENERIC_EVENTS+XM_HM_MAX_ARCH_EVENTS)
        LineError(line, "Event \"%s\" is not permitted in the hypervisor", hmEvents[event]);
    if (!(hmHpvEventsAndActions[event]&TOBIT(action)))
	LineError(line, "Action \"%s\" on event \"%s\" is not permitted", hmActions[action], hmEvents[event]);
}

void HmPartIsActionPermittedOnEvent(int event, int action, int line) {
    if (!(hmPartEventsAndActions[event]&TOBIT(action)))
	LineError(line, "Action \"%s\" on event \"%s\" is not permitted", hmActions[action], hmEvents[event]);
}

void HmCheckExistMaintenancePlan(void) {
    int e, i, maintenance=0;
    // Are there any maintenance action?
    for (e=0;e<(XM_HM_MAX_GENERIC_EVENTS+XM_HM_MAX_ARCH_EVENTS); e++)
        if(xmc.hpv.hmTab[e].action==XM_HM_AC_SWITCH_TO_MAINTENANCE)
            maintenance=1;
    
    for (e=0; e<xmc.noPartitions; e++)
        for (i=0; i<XM_HM_MAX_EVENTS; i++)
            if (xmcPartitionTab[e].hmTab[i].action==XM_HM_AC_SWITCH_TO_MAINTENANCE)
                maintenance=1;       

    if (maintenance)
        // Is there a maintenance plan?
        for (e=0; e<xmc.hpv.noCpus; e++)
            if(xmc.hpv.cpuTab[e].noSchedCyclicPlans<2)
                LineError(xmcNoL.hpv.cpuTab[e].id, "Although required, a maintenance plan is not defined for CPU \"%d\"", xmc.hpv.cpuTab[e].id);
}
