/*
 * $FILE: fpga_xmconf.h
 *
 * IRQS
 *
 * $VERSION$
 *
 * Author: Javier O. Coronel <jacopa@ai2.upv.es>
 *
 * $LICENSE:
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#ifndef _XM_DEV_FPGA_XMCONF_H_
#define _XM_DEV_FPGA_XMCONF_H_

#ifdef CONFIG_DEV_FPGA_ITARFREE

#ifndef _XM_KERNEL_
#include <xm_inc/xmconf.h>
#include <xm_inc/drivers/fpga_itarfree.h>
#else
#include <xmconf.h>
#include <drivers/fpga_itarfree.h>
#endif

/*Events generated by the fpga*/
#define XM_HM_MAX_FPGA_EVENTS        2

/*Label used in the definition of the total numbers of events*/
#define XM_HM_MAX_EXTERNAL_EVENTS    XM_HM_MAX_FPGA_EVENTS

/* <track id="itar-free-hm-events"> */
#define XM_HM_EV_FPGA_ERR_SDRAM    (XM_HM_MAX_GENERIC_EVENTS+19+0)
#define XM_HM_EV_FPGA_EADR         (XM_HM_MAX_GENERIC_EVENTS+19+1)
/* </track id="itar-free-hm-events"> */


/* <track id="itar-free-irq-list"> */
/*Secundary interrupt controller in FPGA*/
#define XM_TRAP_IT_SPW_TX       (CONFIG_NO_HWIRQS+IT_SPW_TX)      //30
#define XM_TRAP_IT_SPW_RX       (CONFIG_NO_HWIRQS+IT_SPW_RX)      //29
#define XM_TRAP_IT_OSLNK_TX     (CONFIG_NO_HWIRQS+IT_OSLNK_TX)    //28
#define XM_TRAP_IT_OSLNK_RX     (CONFIG_NO_HWIRQS+IT_OSLNK_RX)    //27
#define XM_TRAP_IT_IOTOP        (CONFIG_NO_HWIRQS+IT_IOTOP)       //26
#define XM_TRAP_IT_UART_RX      (CONFIG_NO_HWIRQS+IT_UART_RX)     //25
#define XM_TRAP_IT_UART_TX      (CONFIG_NO_HWIRQS+IT_UART_TX)     //24
#define XM_TRAP_IT_IO3          (CONFIG_NO_HWIRQS+IT_IO3)         //23
#define XM_TRAP_IT_IO2          (CONFIG_NO_HWIRQS+IT_IO2)         //22
#define XM_TRAP_IT_IO1          (CONFIG_NO_HWIRQS+IT_IO1)         //21
#define XM_TRAP_IT_IO0          (CONFIG_NO_HWIRQS+IT_IO0)         //20
#define XM_TRAP_IT_32HZ         (CONFIG_NO_HWIRQS+IT_32HZ)        //19
#define XM_TRAP_IT_1HZ          (CONFIG_NO_HWIRQS+IT_1HZ)         //18
#define XM_TRAP_IT_EADR         (CONFIG_NO_HWIRQS+IT_EADR)        //17 XM reserved.
#define XM_TRAP_IT_SDRAM        (CONFIG_NO_HWIRQS+IT_SDRAM)       //16 XM reserved.
/* </track id="itar-free-irq-list"> */
#endif

#endif
